// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortScannerServiceClient is the client API for PortScannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortScannerServiceClient interface {
	ScanPorts(ctx context.Context, in *ScanPortRequest, opts ...grpc.CallOption) (*ScanPortResponse, error)
}

type portScannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortScannerServiceClient(cc grpc.ClientConnInterface) PortScannerServiceClient {
	return &portScannerServiceClient{cc}
}

func (c *portScannerServiceClient) ScanPorts(ctx context.Context, in *ScanPortRequest, opts ...grpc.CallOption) (*ScanPortResponse, error) {
	out := new(ScanPortResponse)
	err := c.cc.Invoke(ctx, "/scanner.PortScannerService/ScanPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortScannerServiceServer is the server API for PortScannerService service.
// All implementations must embed UnimplementedPortScannerServiceServer
// for forward compatibility
type PortScannerServiceServer interface {
	ScanPorts(context.Context, *ScanPortRequest) (*ScanPortResponse, error)
	mustEmbedUnimplementedPortScannerServiceServer()
}

// UnimplementedPortScannerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortScannerServiceServer struct {
}

func (UnimplementedPortScannerServiceServer) ScanPorts(context.Context, *ScanPortRequest) (*ScanPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanPorts not implemented")
}
func (UnimplementedPortScannerServiceServer) mustEmbedUnimplementedPortScannerServiceServer() {}

// UnsafePortScannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortScannerServiceServer will
// result in compilation errors.
type UnsafePortScannerServiceServer interface {
	mustEmbedUnimplementedPortScannerServiceServer()
}

func RegisterPortScannerServiceServer(s grpc.ServiceRegistrar, srv PortScannerServiceServer) {
	s.RegisterService(&PortScannerService_ServiceDesc, srv)
}

func _PortScannerService_ScanPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortScannerServiceServer).ScanPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scanner.PortScannerService/ScanPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortScannerServiceServer).ScanPorts(ctx, req.(*ScanPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortScannerService_ServiceDesc is the grpc.ServiceDesc for PortScannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortScannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scanner.PortScannerService",
	HandlerType: (*PortScannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanPorts",
			Handler:    _PortScannerService_ScanPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
